java_library(
    name = "api",
    visibility = ["//visibility:public"],
    exports = [
        "//lib/repository/api/src/main/java/com/sebster/repository/api",
        "//lib/repository/api/src/main/java/com/sebster/repository/api/orders",
        "//lib/repository/api/src/main/java/com/sebster/repository/api/properties",
        "//lib/repository/api/src/main/java/com/sebster/repository/api/properties/orders",
        "//lib/repository/api/src/main/java/com/sebster/repository/api/properties/specifications",
        "//lib/repository/api/src/main/java/com/sebster/repository/api/specifications",
    ],
)
