alias(
    name = "hobbes",
    actual = "//hobbes/src/main/java/com/sebster/weereld/hobbes:bin",
)

alias(
    name = "image",
    actual = "//hobbes/src/main/java/com/sebster/weereld/hobbes:image",
)
