apiVersion: v1
kind: ConfigMap
metadata:
  name: hobbes-config
  namespace: hobbes
data:
  application-default.properties: |
    telegram.auth-key=<your telegram botapi token>

    hobbes.telegram-from-white-list=<comma separated list of chat ids>
    hobbes.telegram-chat-white-list=<comma separated list of chat ids>

    spring.datasource.url=jdbc:postgresql://<your database host>/<database name>
    spring.datasource.username=<your database user>
    spring.datasource.password=<your database password>
