java_library(
    name = "jpa",
    visibility = ["//visibility:public"],
    exports = [
        "//lib/repository/jpa/src/main/java/com/sebster/repository/jpa",
        "//lib/repository/jpa/src/main/java/com/sebster/repository/jpa/orders",
        "//lib/repository/jpa/src/main/java/com/sebster/repository/jpa/properties",
        "//lib/repository/jpa/src/main/java/com/sebster/repository/jpa/properties/orders",
        "//lib/repository/jpa/src/main/java/com/sebster/repository/jpa/properties/specifications",
        "//lib/repository/jpa/src/main/java/com/sebster/repository/jpa/specifications",
    ],
)
