alias(
    name = "botapi-test",
    actual = "//lib/telegram/botapi-test/src/main/java/com/sebster/telegram/botapi/test",
    visibility = ["//visibility:public"],
)

alias(
    name = "botapi-test-springboot",
    actual = "//lib/telegram/botapi-test/src/main/java/com/sebster/telegram/botapi/test/springboot",
    visibility = ["//visibility:public"],
)
