alias(
    name = "cli",
    actual = "//remarkable/apps/cli/src/main/java/com/sebster/remarkable/cli:bin",
)

alias(
    name = "jar",
    actual = "//remarkable/apps/cli/src/main/java/com/sebster/remarkable/cli:jar",
)
