load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "clock",
    testonly = True,
    srcs = ["TestClock.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//3rdparty/org/projectlombok/lombok",
    ],
)
