java_library(
    name = "api",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//3rdparty/org/projectlombok/lombok",
        "//lib/repository/api",
        "@maven//:junit_junit",
        "@maven//:org_hamcrest_hamcrest",
    ],
)
