alias(
    name = "backup",
    actual = "//remarkable/apps/backup/src/main/java/com/sebster/remarkable/backup:bin",
)

alias(
    name = "jar",
    actual = "//remarkable/apps/backup/src/main/java/com/sebster/remarkable/backup:jar",
)
