apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpbin-ingress
spec:
  rules:
    - host: httpbin.microk8s
      http:
        paths:
          - backend:
              serviceName: httpbin
              servicePort: 8000
            path: /
