apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: httpbin-certificate
  namespace: istio-system
spec:
  secretName: httpbin-certificate
  duration: 24h
  renewBefore: 4h
  commonName: httpbin.microk8s
  dnsNames:
    - httpbin.microk8s
  organization:
    - Insight Information Technologies
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
